// =========================================================================
// src/types.ts
// Shared TypeScript types for GModPanel.
// NOTE: The `Env` interface is auto-generated by `npx wrangler types` into
// worker-configuration.d.ts — do not declare it manually here.
// =========================================================================

// -------------------------------------------------------------------------
// D1 row shapes
// -------------------------------------------------------------------------

export interface UserRow {
	id: string;
	steamid64: string;
	display_name: string | null;
	avatar_url: string | null;
	created_at: number;
	last_login: number | null;
}

export interface ServerRow {
	id: string;
	owner_id: string;
	name: string;
	description: string | null;
	api_key_hash: string;
	created_at: number;
	last_seen: number | null;
	active: number;
}

export interface SnapshotRow {
	id: number;
	server_id: string;
	ts: number;
	map: string | null;
	gamemode: string | null;
	player_count: number | null;
	max_players: number | null;
	fps: number | null;
	tickrate: number | null;
}

export interface EventRow {
	id: string;
	server_id: string;
	ts: number;
	type: string;
	data: string | null;
}

export interface PlayerSessionRow {
	id: string;
	server_id: string;
	steamid64: string;
	player_name: string | null;
	joined_at: number;
	left_at: number | null;
	map: string | null;
}

export interface KillRow {
	id: string;
	server_id: string;
	ts: number;
	killer_steamid: string | null;
	victim_steamid: string;
	weapon: string | null;
	map: string | null;
}

export interface WarningRow {
	id: string;
	server_id: string;
	steamid: string;
	issued_by: string;
	reason: string;
	created_at: number;
	expires_at: number | null;
	active: number;
}

export interface CommandLogRow {
	id: string;
	server_id: string;
	type: string;
	payload: string | null;
	issued_by: string | null;
	status: string;
	created_at: number;
	acked_at: number | null;
}

// -------------------------------------------------------------------------
// Hono context variables
// -------------------------------------------------------------------------

export interface HonoVars {
	server_id?: string;
	user_id?: string;
	steamid64?: string;
	session_token?: string;
}

